### ISSUE TITLE
Deployed agent shows an error with an invalid password

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-ibm-log-analysis-bind#23]
For some reason the api key used to bind the repository has errors and even though the agent is deployed the logs do not stream properly

**Comment by timroster** [comment]
Problem is being caused by invocation of script - the name use in the access key creation is used instead of the value:

https://github.com/cloud-native-toolkit/terraform-ibm-log-analysis-bind/blob/7470b53d116e32cfb299ed694af4fc682e90ec0c/main.tf#L54
